baseURL = "https://miguelsolorio.com"
languageCode = "en-us"
title = "Miguel Solorio"
SectionPagesMenu = "main"

[[menu.main]]
  name = "Twitter"
  weight = 1
  url = "https://twitter.com/miguelsolorio_"

[[menu.main]]
  name = "GitHub"
  weight = 2
  url = "https://github.com/misolori"

[[menu.main]]
  name = "LinkedIn"
  weight = 3
  url = "https://www.linkedin.com/in/miguel-solorio-a432b021"

[[menu.main]]
  name = "VSCO"
  weight = 4
  url = "https://vsco.co/miguel/gallery"