baseURL = "https://miguelsolorio.com"
languageCode = "en-us"
title = "Miguel Solorio"
SectionPagesMenu = "main"

[[menu.main]]
  name = "Work"
  weight = 1
  url = "/"

[[menu.main]]
  name = "Resume"
  weight = 2
  url = "miguel-solorio-resume.pdf"