baseURL = "https://miguelsolorio.com"
languageCode = "en-us"
title = "Miguel Solorio"
SectionPagesMenu = "main"

[[menu.main]]
  name = "Work"
  weight = 1

[[menu.main]]
  name = "Resume"
  weight = 2